# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://${tan.datasource.host}:${tan.datasource.port}/${tan.datasource.database}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${tan.datasource.username}
    password: ${tan.datasource.password}
    driver-class-name: ${tan.datasource.driver-class-name}
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# MyBatis Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.truthgame.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1

# 日志配置
logging:
  level:
    com.truthgame: debug
  file:
    name: logs/truth-game.log

# 服务器配置
server:
  port: 8641

# knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表

wx:
  miniapp:
    app-id: ${tan.wechat.appid}
    app-secret: ${tan.wechat.secret}
  mp:
    app-id: ${tan.wechat.appid}  # 优先使用环境变量
    app-secret: ${tan.wechat.secret}  # 优先使用环境变量